### ISSUE TITLE
semi-supervised evaluation

### ISSUE THREAD

**Issue by fatemehazimi990** [davisvideochallenge/davis2017-evaluation#10]
Hi,

For semi-supervised evaluation, it seems that the last frame is excluded [link](https://github.com/davisvideochallenge/davis2017-evaluation/blob/d34fdef71ce3cb24c1a167d860b707e575b3034c/davis2017/evaluation.py#L85).
The reason for excluding the first frame is clear, but I would appreciate it if you explain the reason for excluding the last frame.
Thank you!

**Comment by scaelles** [comment]
Hello!

The last frame is excluded for historical reasons. In the [DAVIS 2016 paper](https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Perazzi_A_Benchmark_Dataset_CVPR_2016_paper.pdf), some approaches that were benchmarked did not produce a result for the last frame and therefore it was excluded. In order to keep evaluations compatible, we decided not to change it in the following iterations of the DAVIS datasets.

**Comment by fatemehazimi990** [comment]
Thank you for the clarification!
